#!/bin/bash

for test in `find invalid_verif/ -type f`
do
	python -c 'print("="*55)'
	echo -e "File : $test"
	./source/krpsim_verif.py resources/simple $test
	if [ "$?" -eq 0 ] ; then
		echo -e "\e[32m Valid"
	else
		echo -e "\e[31m Invalid"
	fi
	echo -e "\e[0m"
done
